"""Harness core: protocols, schemas, and runtime."""

from harness.core import activity
from harness.core.action_canonicalizer import (
    CanonicalizationResult,
    canonicalize_tool_name,
)
from harness.core.activity import ActivityEvent, ActivityStore
from harness.core.adapter import Adapter
from harness.core.agent_iter import (
    AgentRun,
    AgentRunStep,
    FinalResponseStep,
    ModelRequestStep,
    ToolCallStep,
    ToolResultStep,
)
from harness.core.approval import (
    ApprovalOutcome,
    ApprovalStatus,
    ApprovalStore,
    PendingApproval,
)
from harness.core.budget import ContextBudget, count_tokens, prune
from harness.core.calibration import CalibrationRecord, OutcomeCalibration
from harness.core.compactor import ContextCompactor
from harness.core.critic import Critic, LLMCritic, MultiCritic, make_multi_critic
from harness.core.defense_ledger import (
    DefenseLedger,
    DefenseStat,
    build_ledger,
    correlate_defenses,
    format_ledger,
    parse_ledger_text,
)
from harness.core.env_contract import ContractRegistry, EnvironmentContract
from harness.core.errors import (
    ApprovalDeniedError,
    CancelledError,
    ConfigurationError,
    Handoff,
    HarnessError,
    InternalError,
    ModelUnavailableError,
    NetworkError,
    RateLimitError,
    StallError,
    TimeoutError,
    ToolError,
    ToolRetry,
)
from harness.core.events import (
    Critique,
    Done,
    ErrorEvent,
    Event,
    GuardrailTrippedEvent,
    HandoffEvent,
    ModelRequestEvent,
    PhaseCompletedEvent,
    PhaseStartedEvent,
    PredictionEvent,
    PredictionMismatchEvent,
    StepCompleted,
    StepStarted,
    TextDelta,
    ToolCallEvent,
    ToolResultEvent,
    Verification,
)
from harness.core.failover import ErrorKind, FailoverPolicy, classify
from harness.core.flow import Flow, FlowRunner, listen, persist, router, start
from harness.core.flow_checkpoint import (
    CheckpointStore,
    FileCheckpointStore,
    FlowCheckpoint,
    InMemoryCheckpointStore,
)
from harness.core.guardrails import Guardrail, GuardrailMode, GuardrailResult
from harness.core.handoff import HandoffTool
from harness.core.loop_detector import LoopDetector, LoopFinding, LoopPattern
from harness.core.memory import MemoryEntry, MemoryKind, MemoryStore
from harness.core.orchestrator import (
    AgentDoneEvent,
    AgentEventWrapper,
    AgentRole,
    AgentStartedEvent,
    MultiAgentOrchestrator,
    OrchestratorEvent,
    PlanRejectedEvent,
    ProgressLedger,
    ReplanRequestedEvent,
    StallDetectedEvent,
    WorkItemClaimedEvent,
    WorkItemCompletedEvent,
    WorkItemCreatedEvent,
    WorkItemOrphanedEvent,
    WorkItemRejectedEvent,
    WorkItemVerifiedEvent,
    WorkQueue,
)
from harness.core.planner import LLMPlanner, NoOpPlanner, Plan, PlanContext, Planner, PlanStep
from harness.core.prediction import (
    ConsequencePredictor,
    PredictionOutcome,
    ToolPrediction,
    compare_prediction,
)
from harness.core.procedural_skill import (
    ArtifactTipProvider,
    CompositeTipsProvider,
    MiningInput,
    StaticTipsProvider,
    Tip,
    TipLibrary,
    TipsProvider,
    parse_mined_tips,
    render_mining_prompt,
)
from harness.core.prompt_injection_probe import (
    InjectionFinding,
    annotate_if_suspicious,
    scan_text,
)
from harness.core.repair import RepairDirective, RepairMode, RepairOrchestrator
from harness.core.resume import DEFAULT_RESUME_PATH, FeatureItem, ResumeContract
from harness.core.role_contract import (
    Authority,
    ContractValidation,
    RoleContract,
    filter_tools_by_authority,
    validate_inputs,
    validate_outputs,
)
from harness.core.runtime import Agent, fork_session
from harness.core.schemas import (
    ApprovalDecision,
    Capabilities,
    EffectScope,
    Message,
    Note,
    PhaseStatus,
    Role,
    RunRequest,
    Session,
    SessionStatus,
    ToolCall,
    ToolResult,
    Usage,
    VerificationResult,
)
from harness.core.secret_redaction import has_secrets, redact_secrets
from harness.core.shell_safety import check_dangerous_command
from harness.core.storage import Storage
from harness.core.telemetry import configure_logging, get_logger, span
from harness.core.tools import (
    ApprovalHandler,
    ApprovalPolicy,
    AutoApprove,
    AutoDeny,
    InboxApprovalHandler,
    Tool,
    ToolRegistry,
    tool_matches_phase,
)
from harness.core.tools_memory import NotesTool, PruneLedgerTool
from harness.core.tools_messaging import CheckMessagesTool, NotifyTool
from harness.core.tools_orchestration import (
    CompleteWorkItemTool,
    CreateWorkItemTool,
    ListWorkItemsTool,
)
from harness.core.tools_phases import PhaseTool
from harness.core.tools_verification import RequestCritiqueTool, VerifyWorkTool
from harness.core.verification import (
    BugfixCommentRewriteVerifier,
    ChainedVerifier,
    ClaimGroundingVerifier,
    ConsensusVerifier,
    DiagnosisAlignmentVerifier,
    EvidenceContract,
    EvidenceContractResult,
    FileScopeVerifier,
    LLMJudgeVerifier,
    MinimalFixVerifier,
    MisdirectedSuggestionVerifier,
    NegativeConstraintVerifier,
    PhaseGateVerifier,
    PromptSurfaceRevertVerifier,
    RuleVerifier,
    ShellVerifier,
    StateVerifier,
    TestsBeforeEditVerifier,
    VerificationGateway,
    Verifier,
    VerifierRouter,
    VerifyBeforeDoneVerifier,
    WorkItemJudge,
    evaluate_evidence,
)

__version__ = "0.0.0"

__all__ = [
    "DEFAULT_RESUME_PATH",
    "ActivityEvent",
    "ActivityStore",
    "Adapter",
    "Agent",
    "AgentDoneEvent",
    "AgentEventWrapper",
    "AgentRole",
    "AgentRun",
    "AgentRunStep",
    "AgentStartedEvent",
    "ApprovalDecision",
    "ApprovalDeniedError",
    "ApprovalHandler",
    "ApprovalOutcome",
    "ApprovalPolicy",
    "ApprovalStatus",
    "ApprovalStore",
    "ArtifactTipProvider",
    "Authority",
    "AutoApprove",
    "AutoDeny",
    "BugfixCommentRewriteVerifier",
    "CalibrationRecord",
    "CancelledError",
    "CanonicalizationResult",
    "Capabilities",
    "ChainedVerifier",
    "CheckMessagesTool",
    "CheckpointStore",
    "ClaimGroundingVerifier",
    "CompleteWorkItemTool",
    "CompositeTipsProvider",
    "ConfigurationError",
    "ConsensusVerifier",
    "ConsequencePredictor",
    "ContextBudget",
    "ContextCompactor",
    "ContractRegistry",
    "ContractValidation",
    "CreateWorkItemTool",
    "Critic",
    "Critique",
    "DefenseLedger",
    "DefenseStat",
    "DiagnosisAlignmentVerifier",
    "Done",
    "EffectScope",
    "EnvironmentContract",
    "ErrorEvent",
    "ErrorKind",
    "Event",
    "EvidenceContract",
    "EvidenceContractResult",
    "FailoverPolicy",
    "FeatureItem",
    "FileCheckpointStore",
    "FileScopeVerifier",
    "FinalResponseStep",
    "Flow",
    "FlowCheckpoint",
    "FlowRunner",
    "Guardrail",
    "GuardrailMode",
    "GuardrailResult",
    "GuardrailTrippedEvent",
    "Handoff",
    "HandoffEvent",
    "HandoffTool",
    "HarnessError",
    "InMemoryCheckpointStore",
    "InboxApprovalHandler",
    "InjectionFinding",
    "InternalError",
    "LLMCritic",
    "LLMJudgeVerifier",
    "LLMPlanner",
    "ListWorkItemsTool",
    "LoopDetector",
    "LoopFinding",
    "LoopPattern",
    "MemoryEntry",
    "MemoryKind",
    "MemoryStore",
    "Message",
    "MinimalFixVerifier",
    "MiningInput",
    "MisdirectedSuggestionVerifier",
    "ModelRequestEvent",
    "ModelRequestStep",
    "ModelUnavailableError",
    "MultiAgentOrchestrator",
    "MultiCritic",
    "NegativeConstraintVerifier",
    "NetworkError",
    "NoOpPlanner",
    "Note",
    "NotesTool",
    "NotifyTool",
    "OrchestratorEvent",
    "OutcomeCalibration",
    "PendingApproval",
    "PhaseCompletedEvent",
    "PhaseGateVerifier",
    "PhaseStartedEvent",
    "PhaseStatus",
    "PhaseTool",
    "Plan",
    "PlanContext",
    "PlanRejectedEvent",
    "PlanStep",
    "Planner",
    "PredictionEvent",
    "PredictionMismatchEvent",
    "PredictionOutcome",
    "ProgressLedger",
    "PromptSurfaceRevertVerifier",
    "PruneLedgerTool",
    "RateLimitError",
    "RepairDirective",
    "RepairMode",
    "RepairOrchestrator",
    "ReplanRequestedEvent",
    "RequestCritiqueTool",
    "ResumeContract",
    "Role",
    "RoleContract",
    "RuleVerifier",
    "RunRequest",
    "Session",
    "SessionStatus",
    "ShellVerifier",
    "StallDetectedEvent",
    "StallError",
    "StateVerifier",
    "StaticTipsProvider",
    "StepCompleted",
    "StepStarted",
    "Storage",
    "TestsBeforeEditVerifier",
    "TextDelta",
    "TimeoutError",
    "Tip",
    "TipLibrary",
    "TipsProvider",
    "Tool",
    "ToolCall",
    "ToolCallEvent",
    "ToolCallStep",
    "ToolError",
    "ToolPrediction",
    "ToolRegistry",
    "ToolResult",
    "ToolResultEvent",
    "ToolResultStep",
    "ToolRetry",
    "Usage",
    "Verification",
    "VerificationGateway",
    "VerificationResult",
    "Verifier",
    "VerifierRouter",
    "VerifyBeforeDoneVerifier",
    "VerifyWorkTool",
    "WorkItemClaimedEvent",
    "WorkItemCompletedEvent",
    "WorkItemCreatedEvent",
    "WorkItemJudge",
    "WorkItemOrphanedEvent",
    "WorkItemRejectedEvent",
    "WorkItemVerifiedEvent",
    "WorkQueue",
    "__version__",
    "activity",
    "annotate_if_suspicious",
    "build_ledger",
    "canonicalize_tool_name",
    "check_dangerous_command",
    "classify",
    "compare_prediction",
    "configure_logging",
    "correlate_defenses",
    "count_tokens",
    "evaluate_evidence",
    "filter_tools_by_authority",
    "fork_session",
    "format_ledger",
    "get_logger",
    "has_secrets",
    "listen",
    "make_multi_critic",
    "parse_ledger_text",
    "parse_mined_tips",
    "persist",
    "prune",
    "redact_secrets",
    "render_mining_prompt",
    "router",
    "scan_text",
    "span",
    "start",
    "tool_matches_phase",
    "validate_inputs",
    "validate_outputs",
]
