"""Sandbox-side file/FIFO RPC for SDKs without a common streaming interface.

This module is uploaded beside worker.py inside a uniquely owned control
directory. Request and control paths are generated by Harness, never models.
"""

from __future__ import annotations

import base64
import contextlib
import importlib
import json
import os
import select
import signal
import subprocess
import sys
import time
from pathlib import Path
from typing import Any


def poll(directory: Path) -> dict[str, Any]:
    request = json.loads((directory / "request.json").read_text())
    cap = request["max_output_bytes"]
    raw = (directory / "events").read_bytes()
    output = bytearray()
    result: dict[str, Any] = {
        "pid": None,
        "cwd": None,
        "exit_code": None,
        "status": "running",
        "running": True,
        "truncated": False,
    }
    for line in raw.splitlines(keepends=True):
        if not line.endswith(b"\n"):
            break
        event = json.loads(line)
        kind = event["event"]
        if kind == "started":
            result.update(pid=event["pid"], cwd=event["cwd"])
        elif kind == "output":
            data = base64.b64decode(event["data"])
            remaining = max(0, cap - len(output))
            output.extend(data[:remaining])
            result["truncated"] |= len(data) > remaining
        elif kind == "truncated":
            result["truncated"] = True
        elif kind == "exit":
            result.update(exit_code=event["exit_code"], status=event["reason"], running=False)
        elif kind == "error":
            output.extend(event["message"].encode()[: max(0, cap - len(output))])
            result.update(status="transport_error", running=False)
    if result["running"]:
        pid = int((directory / "supervisor.pid").read_text())
        try:
            os.kill(pid, 0)
            state = Path(f"/proc/{pid}/stat")
            if state.exists() and state.read_text().rpartition(")")[2].split()[0] == "Z":
                result.update(status="transport_error", running=False)
        except ProcessLookupError:
            result.update(status="transport_error", running=False)
    result["output"] = output.decode(errors="replace")
    return result


def control(directory: Path, message: dict[str, Any]) -> None:
    import fcntl

    # Independent SDK calls must not interleave controls larger than PIPE_BUF.
    with (directory / "control.lock").open("ab") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        _write_control(directory, message)


def _write_control(directory: Path, message: dict[str, Any]) -> None:
    raw = json.dumps(message).encode() + b"\n"
    descriptor = os.open(directory / "stdin", os.O_WRONLY | os.O_NONBLOCK)
    try:
        deadline = time.monotonic() + 2
        while raw:
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise TimeoutError("process input channel is blocked")
            _, ready, _ = select.select([], [descriptor], [], remaining)
            if ready:
                try:
                    written = os.write(descriptor, raw)
                    raw = raw[written:]
                except BlockingIOError:
                    continue
    finally:
        os.close(descriptor)


def main() -> None:
    # Import from the same uploaded directory; no Harness installation needed.
    worker = importlib.import_module("worker")

    request_path = Path(sys.argv[1])
    request = json.loads(request_path.read_text())
    request_path.unlink()
    operation = request["operation"]
    directory = Path(__file__).parent / request.get("process_id", "unused")
    if operation == "process_start":
        directory.mkdir(mode=0o700)
        initial = request["request"]
        (directory / "request.json").write_text(json.dumps(initial))
        os.mkfifo(directory / "stdin", mode=0o600)
        # The supervisor holds a read/write descriptor so independent SDK RPCs
        # can deliver controls without EOF between calls. Its deadline remains
        # active even if the SDK client disappears.
        descriptor = os.open(directory / "stdin", os.O_RDWR)
        process: subprocess.Popen[bytes] | None = None
        try:
            with (directory / "events").open("wb") as output:
                process = subprocess.Popen(
                    [sys.executable, "-u", str(Path(__file__).with_name("worker.py"))],
                    stdin=descriptor,
                    stdout=output,
                    stderr=subprocess.DEVNULL,
                    start_new_session=True,
                )
            (directory / "supervisor.pid").write_text(str(process.pid))
            os.close(descriptor)
            descriptor = os.open(directory / "stdin", os.O_WRONLY | os.O_NONBLOCK)
            raw = base64.b64encode(json.dumps(initial).encode()) + b"\n"
            # Request may exceed a pipe buffer. Write in bounded chunks while
            # the worker consumes its initial line.
            deadline = time.monotonic() + 5
            while raw:
                if time.monotonic() > deadline:
                    raise TimeoutError("worker did not accept initial request")
                _, writable, _ = select.select([], [descriptor], [], 0.1)
                if writable:
                    count = os.write(descriptor, raw[:4096])
                    raw = raw[count:]
        except BaseException:
            if process is not None:
                with contextlib.suppress(ProcessLookupError, PermissionError):
                    os.killpg(process.pid, signal.SIGTERM)
            raise
        finally:
            os.close(descriptor)
        result = poll(directory)
    elif operation == "process_poll":
        result = poll(directory)
    elif operation == "process_input":
        control(directory, {"action": "input", "data": request["data"]})
        result = poll(directory)
    elif operation == "process_terminate":
        result = poll(directory)
        if result["running"]:
            try:
                control(directory, {"action": "terminate"})
            except (OSError, TimeoutError):
                with contextlib.suppress(ProcessLookupError, PermissionError):
                    os.killpg(int((directory / "supervisor.pid").read_text()), signal.SIGTERM)
            result = poll(directory)
    else:
        result = worker.files(request)
    print(json.dumps(result), flush=True)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(json.dumps({"error": f"{type(exc).__name__}: {exc}"}), flush=True)
        raise SystemExit(1) from None
